### ISSUE TITLE
Add more json validation

### ISSUE THREAD

**Issue by Hanspagh** [BuddyGG/buddy_matching#100]
We need to do more json validation, since it's really hard to debug why parse player json fails, when we are just throwing errors. 
Ex. sending voicechat as a non array

**Comment by ecly** [comment]
So it's perhaps not that we need more json validation, but rather we need better error messages for when the validation fails?

**Comment by Hanspagh** [comment]
Already started during [that]( https://github.com/BuddyGG/buddy_matching/commit/337b138fce254dc85bc9802520ba54c50e45eb32), but still we don't have a check for stuff like checking that input is an array

**Comment by ecly** [comment]
@Hanspagh We can add that if we want even more explicit errors, otherwise I suppose it'll happen implicitly from a crash. Feel free to add it.

**Comment by Hanspagh** [comment]
I do think it will make debugging a lot easier, I spent a fair amount of time trying to figure why I was getting a Enumerable is not implemented for False error today

**Comment by ecly** [comment]
Alright, in that case we should definitely do it.

**Comment by ecly** [comment]
@Hanspagh was this closed in #101?

**Comment by Hanspagh** [comment]
I don't think so, we could add some more 😊

**Comment by ecly** [comment]
@Hanspagh ah right - we didn't do it properly with neat errors for criteria yet either. Yep, we'll keep it open.
