### ISSUE TITLE
Add stats tracking

### ISSUE THREAD

**Issue by Hanspagh** [BuddyGG/buddy_matching#76]
Track online players, number of matching etc. and serve it.

**Comment by ecly** [comment]
The LeaveTracker implemented on umbrella_conversion can fairly easily be extended to track the amount of channels that it is currently subscribed to. Then we merely need to add functionality for retrieving it from the tracker and serve it. Might make sense to rename it to ChannelTracker if we choose to extend it with this functionality.

**Comment by ecly** [comment]
Closed in #102
